export const ORDER_STATUSES = {
  REQUEST_RECEIVED: { color: "#008DFF", text: "Request Received" },
  PENDING_DISPATCH: { color: "#008DFF", text: "Pending Dispatch" },
  PENDING_RELEASE: { color: "#008DFF", text: "Pending Release" },
  PENDING_RETRY: { color: "#CA8E03", text: "Pending Retry" },
  ESTIMATES_RECEIVED: { color: "#CA8E03", text: "Estimates Received" },
  ESTIMATES_FAILED: { color: "#EF3900", text: "Estimates Failed" },
  ORDER_DISPATCHED: { color: "#008DFF", text: "Order Dispatched" },
  ORDER_FAILED: { color: "#EF3900", text: "Order Failed" },
  ORDER_ASSIGNED: { color: "#041967", text: "Order Assigned" },
  ORDER_UNASSIGNED: { color: "#CA8E03", text: "Order Unassigned" },
  PICKUP_STARTED: { color: "#008DFF", text: "Pickup Started" },
  PICKUP_COMPLETED: { color: "#008DFF", text: "Pickup Completed" },
  IN_TRANSIT: { color: "#008DFF", text: "In Transit" },
  OUT_FOR_DELIVERY: { color: "#EF3900", text: "Out For Delivery" },
  ORDER_DELIVERED: { color: "#041967", text: "Order Delivered" },
  ORDER_DELAYED: { color: "#CA8E03", text: "Order Delayed" },
  ORDER_REDELIVERY: { color: "#CA8E03", text: "Order Redelivery" },
  ORDER_UNDELIVERABLE: { color: "#EF3900", text: "Order Undeliverable" },
  ERROR_EXCEPTION: { color: "#EF3900", text: "Error Exception" },
  ORDER_CANCELLED: { color: "#EF3900", text: "Order Cancelled" },
  PARTIAL_IN_TRANSIT: { color: "#008DFF", text: "Partial In Transit" },
  PARTIAL_DELIVERED: { color: "#041967", text: "Partial Delivered" },
  PARTIAL_EXCEPTION: { color: "#008DFF", text: "Partial Exception" },
  PICKUP_EXCEPTION: { color: "#008DFF", text: "Pickup Exception" },
  PARTIAL_CANCELLED: { color: "#EF3900", text: "Partial Cancelled" },
  EXPIRED: { color: "#EF3900", text: "Expired" },
  RETURNED: { color: "#EF3900", text: "Returned" },
};
